### PR TITLE
added embedded donor form, menu option

### PR DESCRIPTION
**Pull request by bryan-va**
added donor embedded form with basic copy
added menu option
updated home page with donor box link

looking for comments on copy

### CODE REVIEW

**Comment by kenoshabrickk** [comment]
Hey @bryan-va ! I meant to approve this & I'm not sure if I did it right. Thank you for taking care of this.

**Comment by kfinity** [comment]
A side note - thanks for updating the About page. 
I don't think there's currently a way to get to that page from our navigation, but I think we'll want to resurrect it as a corporate info page, with director bios and links to nonprofit docs.

**Comment by kenoshabrickk** [comment]
We have an About page? https://www.linkedin.com/in/aliceetc/

**Comment by kfinity** [comment]
It's mostly Lucy Parsons copy, so I guess we removed all the links that
pointed to it. https://openoversightva.org/about

**Pull request merged**
